services:
  app:
    build:
      context: .
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    networks:
      caddy_net:
    restart: unless-stopped


networks:
  caddy_net:
    external: true
    name: caddy_caddy_net